packages:
  - apps/*
  - packages/*

catalog:
  '@duckdb/duckdb-wasm': 1.33.1-dev64.0
  '@tailwindcss/vite': ^4.3.3
  '@types/node': ^24.13.3
  '@types/react': ^19.2.18
  '@types/react-dom': ^19.2.5
  '@vitejs/plugin-react': ^5.2.0
  lucide-react: ^1.39.0
  react: ^19.2.8
  react-dom: ^19.2.8
  typescript: ^5.9.3
  vite: ^7.3.6
  web-worker: 1.2.0

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
